### ISSUE TITLE
not a great lab, super arbitrary and random

### ISSUE THREAD

**Issue by aviflombaum** [learn-co-curriculum/oo-animal-sorter#1]
I feel like there can be a better lab that teachers you how to build an object that mutates or sorts data, this feels really arbitrary and it's hard to know what you want.

**Comment by SophieDeBenedetto** [comment]
I'm going to replace with lab where students will build nested array of addresses instead of nested array of animals and talk a bit about google maps in readme. i.e. "putting a map on a web page is a common thing. we're learning to write classes that manipulate data for a reason. google maps can take a nested array of locations to drop pins on a map. let's build a class that can produce this nested array..."

@jmburges @aviflombaum

**Comment by AnnJohn** [comment]
Closing issue
