### ISSUE TITLE
Change to the Rspec

### ISSUE THREAD

**Issue by mbrickenworthe** [learn-co-curriculum/oo-animal-sorter#3]
Maybe I'm wrong w/ this, but I think that the rspec needs to be changed for the examples "contains strings of land animals" and "contains strings of sea animals".   Looking at a couple other rpsec in the OO unit, it seems like a new instance of the Class had to be called to check if they contained the right amounts.  

Here is the old code for SEA_ANIMALS: 
 it "contains strings of sea animals" do
      ["marlin", "octopus", "fish"].each do |sea_animal|
        expect(AnimalSorter::SEA_ANIMALS).to include(sea_animal)
      end
    end

(this should fail (right?) because the class hasn't been called so nothing is in the constant.)

And here's what I changed the SEA_ANIMALS and LAND_ANIMALS to:

it "contains strings of land animals" do
      land_beasts = ["aardvark", "cat", "elephant"]
      land_beasts.each do |animalLand|
        AnimalSorter.new(land_beasts).to_a
        expect(AnimalSorter::LAND_ANIMALS).to include(animalLand)
      end
    end

 it "contains strings of sea animals" do
      sea_beasts = ["marlin", "octopus", "fish"]
        sea_beasts.each do |animalSea|
        AnimalSorter.new(sea_beasts).to_a
        expect(AnimalSorter::SEA_ANIMALS).to include(animalSea)
      end
    end

**Comment by BenjaGross** [comment]
@mbrickenworthe since SEA_ANIMALS and LAND_AMIMALS are class constants they are accessible outside of the class without creating a new instance of that class through the `AnimalSorter::SEA_ANIMALS` syntax, so the spec does not need to be changed to function, though feel free to make a pull request and we will take a look at it.

However, as @aviflombaum mentioned in a different issue this lab should probably  be changed to something less contrived.
